version: '3.4'

services:
  azerisiqdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  azerisiq.api:
    build:
      context: ./AzerIsiq
      dockerfile: Dockerfile

volumes:
  mssql_data:
