version: '3.4'

services:
  azerisiqdb:
    container_name: azerisiqdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - azerisiqnetwork

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - azerisiqnetwork

  azerisiq.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - azerisiqdb
    ports:
      - "5252:5252"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - azerisiqnetwork
    restart: on-failure
 
  prometheus:
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - azerisiqnetwork

  grafana:
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - azerisiqnetwork

  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - azerisiqnetwork

  azerisiq.client:
    ports:
      - "3000:3000"
    env_file:
      - ./azer-ishiq-client/.env
    networks:
      - azerisiqnetwork

volumes:
  mssql_data:

networks:
  azerisiqnetwork:


