version: '3.4'

services:
  azerisiqdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  distributedcache:
    image: redis

  prometheus:
    image: prom/prometheus

  grafana:
    image: grafana/grafana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2

  azerisiq.api:
    build:
      context: .
      dockerfile: AzerIsiq/Dockerfile

volumes:
  mssql_data:
  grafana_data:
  prometheus_data:
  elasticsearch_data:

networks:
  azerisiqnetwork:
